#!/bin/bash

ver3=$(python3 --version | sed s/[^0-9]//g)
#ver2=$(python -V 2>&1 | sed s/[^0-9]//g)


if (("ver3">"2"))
 then
 echo "compared two versions of the python. Python3 is newer, and has a larger number. we recommend to choose python3"
 else 
 echo "choose python2"
fi
